### ISSUE TITLE
Fail to register component

### ISSUE THREAD

**Issue by mortocks** [wladiston/mjml-campaignmonitor#2]
I may be doing something wrong but I can't seem to register the components. In reading the documents I think this is the correct method for registering the component after install but I get the follow errors. 

```.mjmlconfig
{
  "packages": [
    "mjml-campaignmonitor/lib/index.js"
  ]
}
```

Throws an error

```
Error when registering custom component :  ......./node_modules/mjml-campaignmonitor/src/index.js ......./node_modules/mjml-campaignmonitor/src/index.js:1
(function (exports, require, module, __filename, __dirname) { export Image from './Image'
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)    at Function.Module._load (internal/modules/cjs/loader.js:529:3)    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by wladpaiva** [comment]
Well, the src folder shouldn't be referenced unless you are compiling the package again. If you just install it as a dependancy you should get it to work.
Here it is a [demo](https://codesandbox.io/s/adoring-darkness-kg86d?fontsize=14&view=editor)
I also noticed that the new beta version of the MJML is throwing an error message. Haven't really worried about it because this plugin is very simple and didn't want to spend much time on it.

**Comment by mortocks** [comment]
Thanks. I didn't think I was referencing src (see `mjml-campaignmonitor/lib/index.js` in original issue. 

From what I can see after downgrading to Mjml version 4.3.1 it is compiling correctly. It just throws errors saying that the markup isn't valid. Not a super important issue as long as it's compiling 😄 

running
`mjml --watch index.mjml -o index.html`

console output (see errors array)

```
Error when registering custom component :  /Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/lib/index.js TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at registerCustomComponent (/Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/node_modules/mjml-core/lib/helpers/mjmlconfig.js:79:40)
    at /Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/node_modules/mjml-core/lib/helpers/mjmlconfig.js:81:7
    at Array.forEach (<anonymous>)
    at registerCustomComponent (/Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/node_modules/mjml-core/lib/helpers/mjmlconfig.js:80:15)
    at /Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/node_modules/mjml-core/lib/helpers/mjmlconfig.js:108:9
    at Array.forEach (<anonymous>)
    at handleMjmlConfig (/Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/node_modules/mjml-core/lib/helpers/mjmlconfig.js:102:12)
    at Object.<anonymous> (/Users/mortocks/Repos/digital-maker-email-templates/node_modules/mjml-campaignmonitor/node_modules/mjml-core/lib/index.js:369:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
Now watching: index.mjml
/Users/mortocks/Repos/digital-maker-email-templates/index.mjml - Change detected
[ { line: 19,
    message:
     'cm-image cannot be used inside mj-column, only inside: mj-attributes',
    tagName: 'cm-image',
    formattedMessage:
     'Line 19 of /Users/mortocks/Repos/digital-maker-email-templates/index.mjml (cm-image) — cm-image cannot be used inside mj-column, only inside: mj-attributes' } ] 'Line 19 of /Users/mortocks/Repos/digital-maker-email-templates/index.mjml (cm-image) — cm-image cannot be used inside mj-column, only inside: mj-attributes'
/Users/mortocks/Repos/digital-maker-email-templates/index.mjml - Successfully compiled
/Users/mortocks/Repos/digital-maker-email-templates/index.mjml - Change detected

[ { line: 19,
    message:
     'cm-image cannot be used inside mj-column, only inside: mj-attributes',
    tagName: 'cm-image',
    formattedMessage:
     'Line 19 of /Users/mortocks/Repos/digital-maker-email-templates/index.mjml (cm-image) — cm-image cannot be used inside mj-column, only inside: mj-attributes' } ] 'Line 19 of /Users/mortocks/Repos/digital-maker-email-templates/index.mjml (cm-image) — cm-image cannot be used inside mj-column, only inside: mj-attributes'
/Users/mortocks/Repos/digital-maker-email-templates/index.mjml - Successfully compiled
```

**Comment by wladpaiva** [comment]
Tried to remove the plugin reference and only run the cmd with the --watch parameter and it gives the same error. I guess that at this point this looks like a MJML bug. Although I like the VSCode plugin to preview and compile the code, I'm using the browser-sync to preview and compile over different devices.
Here it's an example of my package.json
```
{
  "name": "201132",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "mjml index.mjml -o index.html",
    "build:watch": "mjml -w index.mjml -o index.html",
    "clean": "rm -rf dist .cache img.zip index.html",
    "compress": "zip -rj img.zip img",
    "deploy": "npm-run-all clean build compress",
    "serve": "browser-sync start --server --no-notify --no-ghost-mode -f *.html img",
    "develop": "npm-run-all --parallel build:watch serve"
  },
  "devDependencies": {
    "browser-sync": "^2.26.3",
    "mjml": "^4.2.0",
    "npm-run-all": "^4.1.3",
    "mjml-campaignmonitor": "1.0.1"
  }
}
```
